sudo: false
language: python
python:
    - 2.7
    - 3.5
install:
    - pip install -r requirements.txt
    - pip install tox-travis
script:
 - tox
 - coverage run -m py.test
 - coverage report -m

after_success:
 - coveralls
